steps:
- id: filter build
  uses: docker://docker:19.03.3
  runs: [sh, -exc]
  secrets: [ENGINE, WITH_K8S, TRAVIS_PYTHON_VERSION, TRAVIS_PULL_REQUEST]
  args:
  - |
    # skip execution if this is a build for a PR
    # for the rest, only continue if:
    #   1. build is for upstream (getpopper/popper) repo
    #   2. build corresponds to docker,python-3.7,no-k8s element of the matrix
    if [[ $TRAVIS_PULL_REQUEST != false ]] || [[ $GIT_REMOTE_ORIGIN_URL != "https://github.com/getpopper/popper" ]] || [[ $GIT_BRANCH != "master" ]] || [[ $ENGINE != "docker" ]] || [[ $TRAVIS_PYTHON_VERSION != "3.7" ]] || [[ -n WITH_K8S ]]; then
      exit 78
    fi

- id: dockerhub release
  uses: docker://docker:19.03
  secrets: [DOCKER_USERNAME, DOCKER_PASSWORD]
  runs: [sh, -ec]
  args:
  - |
    docker build -t getpopper/popper src/
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

    docker tag getpopper/popper getpopper/popper:$GIT_SHA_SHORT
    docker push getpopper/popper
    docker push getpopper/popper:$GIT_SHA_SHORT

    if [[ -n $GIT_TAG ]]; then
      docker tag getpopper/popper getpopper/popper:v$GIT_TAG
      docker push getpopper/popper:v$GIT_TAG
    fi

- id: pypi release
  uses: docker://python:3.7-buster
  secrets: [PYPI_USERNAME, PYPI_PASSWORD]
  runs: [bash, -ec]
  args:
  - |
    if [[ -n $GIT_TAG ]]; then
      # only upload to pypi tagged releases
      pip install twine
      cd src/
      python setup.py sdist
      twine upload -u "$PYPI_USERNAME" -p "$PYPI_PASSWORD" dist/popper-$GIT_TAG.tar.gz
    fi
