steps:
- id: build docker image
  uses: docker://docker:19.03
  runs: [sh]
  args:
  - -ec
  - |
    docker build -t getpopper/popper:latest src/

    if [ -n "$GIT_TAG" ]; then
      docker tag getpopper/popper:$GIT_SHA_SHORT getpopper/popper:$GIT_TAG
    fi

- id: push-img
  uses: docker://docker:19.03.3
  secrets: [DOCKER_USERNAME, DOCKER_PASSWORD]
  runs: [sh]
  args:
  - -ec
  - |
    # only push from master
    if [ "$GIT_BRANCH" != "master" ]; then
      exit 78
    fi

    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    docker push getpopper/popper:latest

    if [ -n "$GIT_TAG" ]; then
      docker push getpopper/popper:$GIT_TAG
    fi
